### ISSUE TITLE
在首页多加一些描述？

### ISSUE THREAD

**Issue by Nevvea7** [fushenghua/GetHosp#3]
加一些比如“这里搜索出来的都是莆田医院大家不要去”之类的
如果不是之前看了“莆田系医院名单”那个repo 单看网站感觉不太容易知道这是干啥的

**Comment by fushenghua** [comment]
嗯 ，由于才一上午做出来，没有过多组织语言

**Comment by fushenghua** [comment]
@Nevvea7 感谢建议，已push
